---
title: 28Rats 2.0
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  rats:
    title: Rats
    output: false
    Gender:
    - 
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: rats
  values:
    layout: default
    Image: 
    Gender: 
    DOB: 
    Sire: 
    Dam: 
    RIP: 
    Description: 
email: 28keish@gmail.com
description: 'Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.

'
baseurl: 
url: 
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
theme: minima
